apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include "http.labels" . | nindent 4 }}
    app: {{ .Values.appName }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.appName }}
