apiVersion: v1
kind: Service
metadata:
  name: {{ include "http.fullname" . }}
  labels:
    {{- include "http.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "http.selectorLabels" . | nindent 4 }}
