version: '3'

services:
  app:
    build: .
    env_file: .env
#    volumes:
#      - ./popular.txt:/popular.txt
    ports:
      - 3000:3000
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - app
    environment:
      - DOMAIN=app
      - PORT=3000