apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lucksacks
  namespace: default
spec:
  interval: 1m
  url: https://github.com/r33drichards/lucksacks
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/    
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lucksacks
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: charts/http
      version: '0.1.x'
      sourceRef:
        kind: GitRepository
        name: lucksacks
        namespace: default
      interval: 10m
  values:
    replicaCount: 2