init:
	terraform init \
		-backend-config="address=https://gitlab.com/api/v4/projects/26875400/terraform/state/lucksacks" \
		-backend-config="lock_address=https://gitlab.com/api/v4/projects/26875400/terraform/state/lucksacks/lock" \
		-backend-config="unlock_address=https://gitlab.com/api/v4/projects/26875400/terraform/state/lucksacks/lock" \
		-backend-config="username=reedrichards" \
		-backend-config="password=${TOKEN}" \
		-backend-config="lock_method=POST" \
		-backend-config="unlock_method=DELETE" \
		-backend-config="retry_wait_min=5"

plan:
    terraform plan


apply-ecr:
    terraform apply -target=aws_ecr_repository.lucksacks